### ISSUE TITLE
Odd or missing < on loop. Line 344.

### ISSUE THREAD

**Issue by sethleedy** [Mi-Al/WiFi-autopwner#1]
Thinking this is a typo.

`done < <(cat /tmp/wash.all | grep -E '[A-Fa-f0-9:]{11}' | awk '{print $1}' | sed 's/,//')`

**Comment by Mi-Al** [comment]
No, the line is correct. You can review more examples of processing each line received as a result of grep command: https://stackoverflow.com/questions/16317961/how-to-process-each-line-received-as-a-result-of-grep-command
 
By the way, the code is workable, if to add or remove < the script will fail while processing Wash result.

**Comment by sethleedy** [comment]
Cool. Just never seen a spaced < < before.
Ok. Nice script btw.
